sonar.projectKey=dangel34_Compliance-Scanner
sonar.organization=dangel34

sonar.projectName=RuleForge Compliance Scanner
sonar.projectVersion=1.0.2

sonar.sources=.
sonar.exclusions=tests/**,**/__pycache__/**,**/.*,installer/**,build/**,dist/**

sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
